name: remotepower
description: "App Store ve Google Play uyumlu Uzaktan Bilgisayar Açma ve Güç Yönetimi Uygulaması"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  web_socket_channel: ^2.4.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  local_auth: ^2.1.8
  qr_code_scanner: ^1.0.1
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
